version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: cognitive-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${HOST_VOLUMES_PATH}/postgres:/var/lib/postgresql/data
    networks:
      - cognitive-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: cognitive-postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - cognitive-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: cognitive-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ${HOST_VOLUMES_PATH}/redis:/data
    networks:
      - cognitive-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: cognitive-redis-exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"
    networks:
      - cognitive-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus
    container_name: cognitive-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ${HOST_VOLUMES_PATH}/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - cognitive-network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana
    container_name: cognitive-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${HOST_VOLUMES_PATH}/grafana:/var/lib/grafana
    networks:
      - cognitive-network
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cognitive-network: